name:                data-types
version:             0.1.0.0
github:              "poyea/data-types"
license:             BSD3
author:              "John Law"
maintainer:          "johnlaw.po@gmail.com"
copyright:           "2022 John Law"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/poyea/data-types#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  data-types-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-types

tests:
  data-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-types
    - QuickCheck
